# Welcome to Jekyll!
title: SEC Football Schedule
year: 2017
description: >
  The best source for the SEC Football schedule on the web. 
baseurl: ""
url: "https://www.secschedule.com"

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: secschedule-com

# Google
google_analytics: UA-101913363-1

paginate: 5

permalink: /:year/:month/:day/:title/

gems: 
 - jekyll-paginate
 - jekyll-sitemap

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/